language: general
sudo: required

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'currency-converter'
  env: 'Currencyconverter-env'
  bucket_name: 'elasticbeanstalk-us-east-1-736796324192'
  bucket_path: 'currency-converter'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY